name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        env:
          EMAIL_SECRET: ${{secrets.EMAIL}}
          KEY_SECRET: ${{secrets.KEY}}
          PASSWORD_SECRET: ${{secrets.PASSWORD}}
          TOKEN_SECRET: ${{secrets.TOKEN}}
          URL_SECRET: ${{secrets.URL}}
          
        
      
