name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        env:
          CYPRESS_email: ${{secrets.EMAIL}}
          CYPRESS_key: ${{secrets.KEY}}
          CYPRESS_password: ${{secrets.PASSWORD}}
          CYPRESS_token: ${{secrets.TOKEN}}
          CYPRESS_url: ${{secrets.URL}}
          
        
      
